// Generated by CoffeeScript 1.7.1
(function() {
  var CONN_PORT, Connector, PASSWORD, SERVER_URL, STREAM_PORT, USERNAME, api, print;

  Connector = require('./xapi-connector.js');

  process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';

  SERVER_URL = 'xapia.x-station.eu';

  CONN_PORT = '5144';

  STREAM_PORT = '5145';

  USERNAME = '201870';

  PASSWORD = 'rz3smI';

  print = function(msg) {
    return console.log(msg);
  };

  api = new Connector(SERVER_URL, CONN_PORT, STREAM_PORT, USERNAME, PASSWORD);

  api.connect();

  setTimeout(function() {
    return api.conn.send(api.buildCommand('logout', null));
  }, 10000);

}).call(this);
