// Generated by CoffeeScript 1.7.1
(function() {
  var CONN_PORT, Connector, PASSWORD, SERVER_URL, STREAM_PORT, USERNAME, api, print;

  Connector = require('./xapi-connector.js');

  process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';

  SERVER_URL = 'xapia.x-station.eu';

  CONN_PORT = '5144';

  STREAM_PORT = '5145';

  USERNAME = '177509';

  PASSWORD = 'ystk7C';

  print = function(msg) {
    return console.log(msg);
  };

  api = new Connector(SERVER_URL, CONN_PORT, STREAM_PORT, USERNAME, PASSWORD);

  api.onOpen = function(msg) {
    print('Successfuly connected to market server, login in.');
    api.conn.send(api.buildCommand('login', {
      userId: api.username,
      password: api.password
    }));
  };


  /*lets just forward the message to an appropriate handler defined later
  we will use the customTag to know which handler we should forward to
  this module by default builds a custom tag so that it has a unique ID
  and a command property
   */

  api.onMessage = function(msg) {
    print("Received a  message, " + msg);
    msg = JSON.parse(msg);
    print("Received response to command: " + this.env.messages[msg.customTag].command);
    if (api.handlers[this.env.messages[msg.customTag].command] != null) {
      api.handlers[this.env.messages[msg.customTag].command](msg);
    } else {
      throw new Error('There is no handler for this msg');
    }
  };

  api.onError = function(err) {
    print(err);
  };

  api.onClose = function() {
    print('Successfuly closed the connection');
  };

  api.handlers = {
    login: (function(_this) {
      return function(msg) {
        print('Entering login handler');
        if (msg.status === true) {
          api.env.stream_session_id = msg.streamSessionId;
          print('The login was succesfull. Lets check if the API version is 3.0');
          api.conn.send(api.buildCommand('getVersion', null));
        } else {
          print('There was an error login in');
        }
      };
    })(this),
    getVersion: (function(_this) {
      return function(msg) {
        print('Entering getVersion handler');
        if (msg.returnData.version === '3.0') {
          print('The API version is OK. Now lets connect to the stream');
          api.connectStream();
        } else {
          print('The version of the API has changed. This wrapper is outdated');
        }
      };
    })(this),
    logout: (function(_this) {
      return function(msg) {
        print('Entering logout handler, closing sockets');
        if (msg.status === true) {
          api.conn.end();
        }
      };
    })(this)
  };

  api.onStreamOpen = function(msg) {
    print('Successfuly connected to stream server, subscribing to indicators.');
    api.stream.send(api.buildStreamCommand("getAccountIndicators", api.env.stream_session_id));
    print('Lets also subscribe to EURUSD tick prices');
    api.stream.send(api.buildStreamCommand("getTickPrices", api.env.stream_session_id, ['EURUSD']));
  };


  /*lets just forward the message to an appropriate stream handler defined later
  we will use the customTag to know which handler we should forward to
   */

  api.onStreamMessage = function(msg) {
    msg = JSON.parse(msg);
    print("Received response to command: " + msg.command);
    if (api.stream_handlers[msg.command] != null) {
      api.stream_handlers[msg.command](msg);
    } else {
      throw new Error('There is no handler for this msg');
    }
  };

  api.onStreamError = function(err) {
    print(err);
  };

  api.onStreamClose = function() {
    print('Successfuly closed the stream');
  };

  api.stream_handlers = {
    indicators: (function(_this) {
      return function(msg) {
        print(JSON.stringify(msg));
      };
    })(this),
    tickPrices: (function(_this) {
      return function(msg) {
        print(JSON.stringify(msg));
      };
    })(this)
  };

  api.connect();

  setTimeout(function() {
    return api.conn.send(api.buildCommand('logout', null));
  }, 10000);

}).call(this);
