// Generated by CoffeeScript 1.7.1

/*
The Dispatcher class.
It takes asynchronous requests to send something through the stream
and sends it asynchronously in intervals.
To maximize the speed of sending the messages to the API, we will take advantage
of the fact that we can send 5 requests in less than 200ms intervals.
The API measures how many times we send messages in <200ms intervals.
If we send a message in <200ms interval the API counts this as a 'sin'.
The API counts our sins and we can't have more than 6 of those.
Each time we send a message in >200ms one sin is substrated
 */

(function() {
  var Debugger, Dispatcher, d;

  Debugger = require('debug-js');

  d = new Debugger('Dispatcher', 'green');

  Dispatcher = (function() {
    function Dispatcher(stream, delay, que, last, clearing_que, max_sins) {
      this.stream = stream;
      this.delay = delay != null ? delay : 0;
      this.que = que != null ? que : [];
      this.last = last != null ? last : 0;
      this.clearing_que = clearing_que != null ? clearing_que : false;
      this.max_sins = max_sins != null ? max_sins : 0;
      this.sins = 0;
    }

    Dispatcher.prototype.add = function(msg) {
      this.que.push(msg);
      if (this.clearing_que === false) {
        return this.clearQue();
      }
    };

    Dispatcher.prototype.clearQue = function() {
      var diff, msg;
      this.clearing_que = true;
      diff = new Date().getTime() - this.last;
      if (diff > this.delay || this.sins < this.max_sins) {
        d.debug("Sending message: " + (msg = this.que.shift()) + " \n");
        this.stream.write(msg);
        this.last = new Date().getTime();
        if (diff > this.delay) {
          if (this.sins > 0) {
            this.sins -= 1;
          }
        } else {
          this.sins += 1;
        }
        if (this.que.length > 0) {
          return this.clearQue();
        } else {
          return this.clearing_que = false;
        }
      } else {
        return setTimeout(this.clearQue.bind(this), this.delay + 1 - diff);
      }
    };

    return Dispatcher;

  })();

  module.exports = Dispatcher;

}).call(this);
