// Generated by CoffeeScript 1.7.1
(function() {
  var CONN_PORT, Connector, Debugger, PASSWORD, SERVER_URL, STREAM_PORT, USERNAME, api, c, s;

  Connector = require('./xapi-connector.js');

  Debugger = require('debug-js');

  process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';

  SERVER_URL = 'xapia.x-station.eu';

  CONN_PORT = '5144';

  STREAM_PORT = '5145';

  USERNAME = '177509';

  PASSWORD = 'ystk7C';

  s = new Debugger('Stream', 'blue');

  c = new Debugger('Conn', 'yellow');

  api = new Connector(SERVER_URL, CONN_PORT, STREAM_PORT, USERNAME, PASSWORD);

  api.onOpen = function(msg) {
    c.debug('Successfuly connected to market server, login in.');
    api.conn.send(api.buildCommand('login', {
      userId: api.username,
      password: api.password
    }, 'login'));
  };


  /*lets just forward the message to an appropriate handler defined later
  we will use the customTag to know which handler we should forward to
   */

  api.onMessage = function(msg) {
    c.debug("Received a  message, " + msg);
    msg = JSON.parse(msg);
    c.debug("Received response to command: " + msg.customTag);
    if (api.handlers[msg.customTag] != null) {
      api.handlers[msg.customTag](msg);
    } else {
      throw new Error('There is no handler for this msg');
    }
  };

  api.onError = function(err) {
    c.debug(err);
  };

  api.onClose = function() {
    c.debug('Successfuly closed the connection');
  };

  api.handlers = {
    login: (function(_this) {
      return function(msg) {
        c.debug('Entering login handler');
        if (msg.status === true) {
          api.env.stream_session_id = msg.streamSessionId;
          c.debug('The login was succesfull. Lets check if the API version is 3.0');
          api.conn.send(api.buildCommand('getVersion', null, 'getVersion'));
        } else {
          c.debug('There was an error login in');
        }
      };
    })(this),
    getVersion: (function(_this) {
      return function(msg) {
        c.debug('Entering getVersion handler');
        if (msg.returnData.version === '3.0') {
          c.debug('The API version is OK. Now lets connect to the stream');
          api.connectStream();
        } else {
          c.debug('The version of the API has changed. This wrapper is outdated');
        }
      };
    })(this),
    logout: (function(_this) {
      return function(msg) {
        c.debug('Entering logout handler, closing sockets');
        if (msg.status === true) {
          api.conn.end();
        }
      };
    })(this)
  };

  api.onStreamOpen = function(msg) {
    s.debug('Successfuly connected to stream server, subscribing to indicators.');
    api.stream.send(api.buildStreamCommand("getAccountIndicators", api.env.stream_session_id));
    s.debug('Lets also subscribe to EURUSD tick prices');
    api.stream.send(api.buildStreamCommand("getTickPrices", api.env.stream_session_id, ['EURUSD']));
  };


  /*lets just forward the message to an appropriate stream handler defined later
  we will use the customTag to know which handler we should forward to
   */

  api.onStreamMessage = function(msg) {
    msg = JSON.parse(msg);
    s.debug("Received response to command: " + msg.command);
    if (api.stream_handlers[msg.command] != null) {
      api.stream_handlers[msg.command](msg);
    } else {
      throw new Error('There is no handler for this msg');
    }
  };

  api.onStreamError = function(err) {
    s.debug(err);
  };

  api.onStreamClose = function() {
    s.debug('Successfuly closed the stream');
  };

  api.stream_handlers = {
    indicators: (function(_this) {
      return function(msg) {
        s.debug(JSON.stringify(msg));
      };
    })(this),
    tickPrices: (function(_this) {
      return function(msg) {
        s.debug(JSON.stringify(msg));
      };
    })(this)
  };

  api.connect();

  setTimeout(function() {
    return api.conn.send(api.buildCommand('logout', null, 'logout'));
  }, 10000);

}).call(this);
