// Generated by CoffeeScript 1.7.1
(function() {
  var CONN_PORT, PASSWORD, SERVER_URL, STREAM_PORT, USERNAME, Wrapper, client, print;

  process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';

  Wrapper = require('../lib/xapi-wrapper.js');

  SERVER_URL = 'xapia.x-station.eu';

  CONN_PORT = '5144';

  STREAM_PORT = '5145';

  USERNAME = '201870';

  PASSWORD = 'rz3smI';

  print = function(msg) {
    console.log(msg);
  };

  client = new Wrapper(SERVER_URL, CONN_PORT, STREAM_PORT, USERNAME, PASSWORD);

  client.on('open', function() {
    print("Successfuly connected, loging in.");
    return client.login({
      userId: client.username,
      password: client.password
    });
  });

  client.on('login', function(req, res) {
    print("successfully logged in. \nreq: " + (JSON.stringify(req)) + " \nres: " + (JSON.stringify(res)));
    client.env.stream_session_id = res.streamSessionId;
    return client.connectStream();
  });

  client.on('logout', function(msg) {
    print("Successfuly loged out");
    return client.disconnect();
  });

  client.onStream('open', function() {
    print("Successfuly connected to stream. Subscribing to EURUSD.");
    return client.subscribeTickPrices(client.env.stream_session_id, ['EURUSD']);
  });

  client.onStream('tickPrices', function(msg) {});

  client.connect();

  setTimeout(function() {
    return client.logout();
  }, 100000);

}).call(this);
